### ISSUE TITLE
Link issue

### ISSUE THREAD

**Issue by endian02** [suchoX/PlacePicker#1]
Hi,

I'm trying to use your PlacePicker today with my mPayback app, but get this problem:

Android resource linking failed
C:\Users\bk_ek\.gradle\caches\transforms-2\files-2.1\9ade9861d6f545ab46f51eec7cafdfd0\res\layout\bottom_sheet_view.xml:10: error: attribute fabSize (aka net.endian.mPayback:fabSize) not found.
C:\Users\bk_ek\.gradle\caches\transforms-2\files-2.1\9ade9861d6f545ab46f51eec7cafdfd0\res\layout\bottom_sheet_view.xml:10: error: attribute layout_anchor (aka net.endian.mPayback:layout_anchor) not found.
C:\Users\bk_ek\.gradle\caches\transforms-2\files-2.1\9ade9861d6f545ab46f51eec7cafdfd0\res\layout\bottom_sheet_view.xml:10: error: attribute layout_anchorGravity (aka net.endian.mPayback:layout_anchorGravity) not found.
C:\Users\bk_ek\.gradle\caches\transforms-2\files-2.1\9ade9861d6f545ab46f51eec7cafdfd0\res\layout\bottom_sheet_view.xml:25: error: attribute layout_behavior (aka net.endian.mPayback:layout_behavior) not found.
error: failed linking file resources.

**Comment by suchoX** [comment]
@endian02 Thanks for pointing out the issue:

If you are using AndroidX artifacts you need: 
```
 implementation 'com.google.android.material:material:1.1.0-alpha01'
```  

If you are using trandiotional libraries you need:
```
 implementation 'com.android.support:design:28.0.0'
```
I updated the Readme as well
