### ISSUE TITLE
how to add pins on map?

### ISSUE THREAD

**Issue by haldertaer** [suchoX/PlacePicker#10]
how can I add pins in the map after giving it coordinates?

**Comment by suchoX** [comment]
@haldertaer You cannot. It's a place Picker. There should be no pins other than the one which is used to pick the place. Closing this as it's not an issue

**Comment by haldertaer** [comment]
Thanks for your answer. Would it be possible to add this as a feature?

**Comment by suchoX** [comment]
@haldertaer I do not see the point. Since it's a place picker, I would prefer there be one pin or else may cause confusion and clutter.
