### ISSUE TITLE
how to start off with the user's location?

### ISSUE THREAD

**Issue by haldertaer** [suchoX/PlacePicker#11]
how can I start off the app with the user's current location instead of given coordinates?

**Comment by suchoX** [comment]
You need to fetch user location in your app after asking for user permission and that will give you the Latitude and Longitude which you can use to initialize the library with. PlacePicker doesn't and shouldn't handle permissions. Closing this as it's not an issue.

**Comment by haldertaer** [comment]
Thanks for your answer. Would it be possible to add this as a feature?

**Comment by haldertaer** [comment]
Starting off with the user's location would make more sense.

**Comment by haldertaer** [comment]
Like the original Google Place Picker did (which was unfortunately deprecated)

**Comment by haldertaer** [comment]
You can easily do it in 30 minutes 👍

**Comment by haldertaer** [comment]
Thanks for your answer. Would it be possible to add this as a feature? Like the original Google Place Picker did (which was unfortunately deprecated). Starting off with the user's location would make more sense. It'll probably take you no more than an hour 👍 Just my recommendation.
