### ISSUE TITLE
Theme gets messed up when including this lib

### ISSUE THREAD

**Issue by tpoetsch** [suchoX/PlacePicker#2]
As soon as I include add your library to my gradle file, the theme of my entire app gets messed up. It somehow removes all toolbars of all activities and other theme related attributes. 
Any idea why this is the case?
Thanks

**Comment by suchoX** [comment]
@tpoetsch Looking into it. I have mentioned the style in the Library, maybe that's replacing it.

**Comment by suchoX** [comment]
@tpoetsch The issue has been fixed in version 0.1.5. Readme has been updated as well. Thank you so much for pointing it out.
