### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics

### ISSUE THREAD

**Issue by Luisstevie** [suchoX/PlacePicker#22]
I tried to use your lib, but I had this issue when I was trying to launch by this code:

`
 Intent intent = new PlacePicker.IntentBuilder()
                    .setLatLong(latLng.latitude, latLng.longitude)  
                    .showLatLong(true)
                    .setAddressRequired(true)
                    .hideMarkerShadow(true)
                    .setMarkerImageImageColor(R.color.colorPrimary)
                    .setMapRawResourceStyle(R.raw.map_style)
                    .disableBootomSheetAnimation(true)
                    .onlyCoordinates(true)
                    .build(getBaseActivity());
            startActivityForResult(intent, Constants.PLACE_PICKER_REQUEST);`

and the err logs: 
>    Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlin.jvm.internal.Intrinsics" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/chat.social.free.text.messaging-sYeyXSfWWb0WtUfIEHp01Q==/base.apk"],nativeLibraryDirectories=[/data/app/chat.social.free.text.messaging-sYeyXSfWWb0WtUfIEHp01Q==/lib/arm64, /system/lib64]]

**Comment by prinztob** [comment]
I have the same problem. What was your solution? Thanks
