### ISSUE TITLE
What is the R.raw file ? 

### ISSUE THREAD

**Issue by Ahmedibrahim66** [suchoX/PlacePicker#24]
in the 
""
.setMapRawResourceStyle(R.raw.map_style)  //Set Map Style
"" 

what is the R.raw file ? should it come with the library ? or should i add it manually ? because the code does not work without it in java 

thanks

**Comment by Ahmedibrahim66** [comment]
I tried to download your app but the map color is blue why is that ?

**Comment by suchoX** [comment]
@Ahmedibrahim66 raw file is the map style text which you can get from [https://mapstyle.withgoogle.com/](here)
What do you mean by map color is blue?
