### ISSUE TITLE
Using theme from app

### ISSUE THREAD

**Issue by drmrbrewer** [suchoX/PlacePicker#28]
I can see that it's possible to customise some parts of the picker, with:

	.setFabColor(R.color.fabColor)
	.setPrimaryTextColor(R.color.primaryTextColor) // Change text color of Shortened Address
	.setSecondaryTextColor(R.color.secondaryTextColor) // Change text color of full Address
	.setMapRawResourceStyle(R.raw.map_style) //Set Map Style (https://mapstyle.withgoogle.com/)

It doesn't at present seem possible to set the colour of the Bottom Sheet: it always shows in a "light" theme.

Is it possible to have PlacePicker just follow the app's underlying theme, which can change between day and night mode?  Specifically, I have based my app theme on [this approach](https://material.io/develop/android/theming/dark/).

P.S. I'm similarly trying to get the [Place Autocomplete](https://developers.google.com/places/android-sdk/autocomplete) component to follow the app theme... any hints there?

**Comment by suchoX** [comment]
Now, `PlacePickerActivity` will take the default App theme, or. you can set a custom theme for it, as mentioned in Readme. Also, added `setBottomViewColor()` for setting color to bottom view background color
