### ISSUE TITLE
Getting Individual Address Lines

### ISSUE THREAD

**Issue by fadsel** [suchoX/PlacePicker#30]
Hi There,
Nice library BTW, Great Job!

Is there **any API** for getting the **Individual Adress Lines**, currently there is only` getLatitude()` and `getLongitude()`

You see `data.getParcelableExtra(Constants.ADDRESS_INTENT).toString()`
produces 

> `[Address[addressLines=[0:"Bus Station, Msimbazi, Julius K. Nyerere Rd, Dar es Salaam, Tanzania"],feature=Bus Station,admin=Dar es Salam,sub-admin=Ilala,locality=Dar es Salaam,thoroughfare=Julius K. Nyerere Road,postalCode=null,countryCode=TZ,countryName=Tanzania,hasLatitude=true,latitude=-6.8274729999999995,hasLongitude=true,longitude=39.2756617,phone=null,url=null,extras=null]]`

It will be awesome if we can also get those separate attributes.
Or we should just implement it ourselves, am I missing something?

**Comment by fadsel** [comment]
Just ignore this issue,
a simple ...
`android.location.Address that_address = addressData.getAddressList().get(0)`
did the trick :smile:

**Comment by pauril2** [comment]
Heeeey. How do i get Latitude and longitude separately?
