### ISSUE TITLE
Android resource linking failed

### ISSUE THREAD

**Issue by ars27196** [suchoX/PlacePicker#7]
I have added dependency as you suggested also migrated to AndroidX but getting this error while building the project.
`Android resource linking failed
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:9: error: attribute layout_constraintBottom_toBottomOf (aka com.example.android.shushme:layout_constraintBottom_toBottomOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:9: error: attribute layout_constraintEnd_toEndOf (aka com.example.android.shushme:layout_constraintEnd_toEndOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:9: error: attribute layout_constraintStart_toStartOf (aka com.example.android.shushme:layout_constraintStart_toStartOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:9: error: attribute layout_constraintTop_toTopOf (aka com.example.android.shushme:layout_constraintTop_toTopOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:22: error: attribute layout_constraintBottom_toBottomOf (aka com.example.android.shushme:layout_constraintBottom_toBottomOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:22: error: attribute layout_constraintEnd_toEndOf (aka com.example.android.shushme:layout_constraintEnd_toEndOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:22: error: attribute layout_constraintRight_toRightOf (aka com.example.android.shushme:layout_constraintRight_toRightOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:22: error: attribute layout_constraintStart_toStartOf (aka com.example.android.shushme:layout_constraintStart_toStartOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:22: error: attribute layout_constraintTop_toTopOf (aka com.example.android.shushme:layout_constraintTop_toTopOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:22: error: attribute layout_constraintVertical_bias (aka com.example.android.shushme:layout_constraintVertical_bias) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:35: error: attribute layout_constraintBottom_toBottomOf (aka com.example.android.shushme:layout_constraintBottom_toBottomOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:35: error: attribute layout_constraintEnd_toEndOf (aka com.example.android.shushme:layout_constraintEnd_toEndOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:35: error: attribute layout_constraintStart_toStartOf (aka com.example.android.shushme:layout_constraintStart_toStartOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:35: error: attribute layout_constraintTop_toTopOf (aka com.example.android.shushme:layout_constraintTop_toTopOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:48: error: attribute layout_constraintBottom_toBottomOf (aka com.example.android.shushme:layout_constraintBottom_toBottomOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:48: error: attribute layout_constraintEnd_toEndOf (aka com.example.android.shushme:layout_constraintEnd_toEndOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:48: error: attribute layout_constraintStart_toStartOf (aka com.example.android.shushme:layout_constraintStart_toStartOf) not found.
C:\Users\ars27\.gradle\caches\transforms-2\files-2.1\918612e42f2825c7c648b08fa708bca0\res\layout\activity_place_picker.xml:48: error: attribute layout_constraintTop_toTopOf (aka com.example.android.shushme:layout_constraintTop_toTopOf) not found.
error: failed linking file resources.`

**Comment by suchoX** [comment]
@ars27196 Can you try adding ConstraintLayout dependency on your project?

**Comment by ars27196** [comment]
How stupid of me, thanks it works now. What should I do get the id of the place selected, I need it for location API.

**Comment by suchoX** [comment]
I will refactor my code within a few days to remove such direct dependency! Thanks for pointing out though
