### ISSUE TITLE
No FAB on Android 5 and 6

### ISSUE THREAD

**Issue by kungufli** [suchoX/PlacePicker#8]
I'm testing this PlacePicker (that, by the way, is really very useful, thanks for it!) on my project and I noticed that on two test device with Android 6.0.1 (Nexus 5) and Android 5.1.1 (Huawei P7) the FAB to confirm the location is completely missing. On Android 9 (Pixel 3) it's working fine. It's possible that I'm missing something?

**Comment by suchoX** [comment]
@kungufli Whoa. Thats bad. Can you try out older versions of the library `0.1.4` / `0.1.5` and see if the issue persists. It will help me in fixing the issue.

**Comment by kungufli** [comment]
Sure, just tested right now and I'm experiencing the same behaviour in versions `0.1.6`, `0.1.5` and `0.1.4`

**Comment by suchoX** [comment]
@kungufli Got it. I will look into it and fix it asap. Will keep you posted.

**Comment by suchoX** [comment]
@kungufli I am not getting this issue. Tried on Android 5.0 and 6.0. I have a test application which is in Kotlin and AndroidX. Following is my dependency list:

```
implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.gms:play-services-maps:16.1.0'
    implementation 'com.sucho:placepicker:0.1.6'
```

Anything from the above that's missing for you?

**Comment by kungufli** [comment]
It seems that the cause of the problem is that I'm using a different version of `appcompat`:

`implementation 'androidx.appcompat:appcompat:1.1.0-beta01'`

If I set `androidx.appcompat:appcompat:1.0.2` it works fine. 
However I'm using FABs without any problem in my app with `androidx.appcompat:appcompat:1.1.0-beta01`, do you have any ideas why it's not working in the `PlacePicker`?

**Comment by suchoX** [comment]
@kungufli Probably its a bug. I don't see any other reason why. Glad it got solved, so closing this now. Feel free to reopen this if the issue re surfaces
