### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;

### ISSUE THREAD

**Issue by haldertaer** [suchoX/PlacePicker#9]
I get this error when compiling the java version, you can try it:

java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;

Please update :)

**Comment by suchoX** [comment]
@haldertaer You need to have Kotlin support for your application

**Comment by haldertaer** [comment]
But all my project files are already java-based. How can I do it?

**Comment by suchoX** [comment]
@haldertaer You just need to give support of Kotlin in your application since this library is written in Kotlin. You can use the library from your Java project. 

in your app level build.gradle

`implementation"org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"`

and in your project level build.gradle 

` classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"`

**Comment by haldertaer** [comment]
I tried that already but i get this error: ERROR: Could not get unknown property 'kotlin_version' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by suchoX** [comment]
@haldertaer Kotlin version is a declared variable. I do not know what version of Kotlin your Android studio is using. Replace it with the an actual version number. I use `1.3.21`

**Comment by haldertaer** [comment]
I use the latest version which is 1.3.40-release-Studio3.4-1. But I still receive the same error.

**Comment by suchoX** [comment]
@haldertaer Please Make sure that Kotlin support is added to your project and Kotlin code compiles. This issue will solve then like this issue here: https://github.com/DanielMartinus/Konfetti/issues/47

If it doesn't then let me know.

**Comment by suchoX** [comment]
@haldertaer Closing this because this is most probably not a library issue. Feel free to reopen this if the issue persists
